djangojs/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('js.urls', namespace='js')),

]

js/urls.py
from django.conf.urls import url, include
from .views import *


urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^add/', add, name="add"),
    url(r'^search/', search, name="search"),
]

js/models.py
from django.db import models


class Data(models.Model):
    name = models.CharField(max_length=100)
    number = models.PositiveIntegerField()

    def __str__(self):
        return self.name

js/forms.py
from django import forms
from .models import *

class TableForm(forms.ModelForm):
    class Meta:
        model = Data
        fields = [
            'name',
            'number',
        ]

js/views.py
from django.shortcuts import render, redirect
from django.http import  JsonResponse, HttpResponse
from .models import *
from django.db.models import Q
from .forms import *
from django.template.loader import render_to_string
from django.core import serializers
import json


def index(request):
    data = Data.objects.all()
    context = {
        'data': data,
    }
    return render(request, 'js/index.html', context)
    # return JsonResponse('hi', safe=False)


def add(request):
    data = Data.objects.all()
    data_json =serializers.serialize('json',data)
    data_dumps = json.dumps(data_json)
    # print('data')
    # print(data)
    # print('data_json')
    # print(data_json)
    # print('data_dumps')
    # print(data_dumps)
    if request.method == 'POST':
        form = TableForm(request.POST)
        if form.is_valid():
            form.save()
            # if request.is_ajax():
            #     print("hi")
            #     html = render_to_string('js/add.html', {'form':form}, request=request)
            #     return JsonResponse({'form':html})
            # html = render_to_string('js/add.html', {'form': form}, request=request)
            # return JsonResponse({'form':html})
            # return JsonResponse(data_json,safe=False)
            return HttpResponse(data_json, content_type="application/json")
            # return JsonResponse('hi',safe=False)
            # return redirect('js:add')

    else:
        form = TableForm()
    return render(request, 'js/add.html', {'form':form, 'data':data})


def search(request):
    if request.method == 'POST':
        s = request.POST['search']
        # if s:
        sa = Data.objects.filter(Q(name__icontains=s)|Q(number__icontains=s))
            # if sa:
            #     return render(request, 'js/search.html', {'data': sa,'t':s})
            # else:
            #     return render(request, 'notfound.html')
        return render(request, 'js/search.html', {'data': sa, 't': s})
        # else:
        #     return redirect('js:index')

templates/base.html
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
        <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>

    </head>
    <body>
        {% block content %}
        {% endblock %}
    </body>

</html>
<script type="text/javascript">

        var table = $('#myTable').dataTable();
        table.on( 'draw', function () {
            alert( 'Table redrawn' );
        } );
        <!--$('myform').submit(function(event){-->
            <!--alert("sjfg");-->
            <!--event.preventDefualt();-->
            <!--$.ajax({-->
                <!--type:'POST',-->
                <!--url:'{% url 'js:add' %}',-->
                <!--data:{-->
                    <!--name:$('#name').val(),-->
                    <!--number:$('#number').val(),-->
                    <!--csrfmiddlewaretoken:'{{csrf_token}}',-->
                <!--},-->
                <!--dataType:'json',-->
                <!--success:function(response){-->
                    <!--$('#myform').html(response['form'])-->
                    <!--console.log($('#myform').html(response['form']));-->
                <!--},-->
                <!--error:function(rs, e){-->
                    <!--console.log(rs.responseText);-->
                <!--},-->
            <!--});-->
        <!--});-->

    <!--let data = {};-->
    <!--let url = '{% url 'js:add' %}';-->
    <!--let formNode = document.getElementById('myform').querySelectorAll('input');-->
    <!--let nodeArray = Array.from(formNode);-->
    <!--nodeArray[2].addEventListener('click',submitData);-->

    <!--function submitData(e){-->
        <!--e.preventDefault();-->
        <!--nodeArray.splice(0,3).map(function(item){-->
          <!--data[item.name]=item.value;-->
        <!--});-->
        <!--console.log(data) //  Form Data-->
        <!--fetch(url, {-->
            <!--method: 'POST',-->
            <!--body: JSON.stringify(data),-->
            <!--headers: {-->
            <!--"Content-type": "application/json"-->
            <!--}-->
        <!--})-->
        <!--.then(response => response.json())-->
        <!--.then(json => console.log(json))-->
        <!--.catch(error => console.error('Error:', error));-->
    <!--}-->

    </script>

templates/js/adadsd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

    <form action="" method="post" id="myform">
        <input type="text" name="title" id="name" /><br/>
        <input type="text" name="body" /><br/>
        <input type="number" name="userId" id="number" /><br/>
        <input type="submit" value="Submit" />
    </form>
</body>
<script>
    let data = {};
    let url = 'https://cameronnokes.com/slack-ron-swanson-quote-bot/ron';
    let formNode = document.getElementById('myform').querySelectorAll('input');
    let nodeArray = Array.from(formNode);
    nodeArray[3].addEventListener('click',submitData);

    function submitData(e){
        e.preventDefault();
        nodeArray.splice(0,3).map(function(item){
          data[item.name]=item.value;
        });
        console.log(data) //  Form Data
        fetch(url, {
            method: 'POST',
            body: JSON.stringify(data),
            headers: {
            "Content-type": "application/json"
            }
        })
        .then(response => response.json())
        .then(json => console.log(json))
        .catch(error => console.error('Error:', error));
    }
</script>
</html>

templates/js/add.html
{% extends 'base.html' %}
{% block content %}

    <form action="" method="post" id="myform">
        {% csrf_token%}
        <!--{{form.as_p}}-->
        <input type="text" name="name" id="name" /><br/>
        <input type="number" name="number" id="number" /><br/>
        <input type="submit" value="Submit" />
    </form>
<br/>
<table id="myTable" class="table" data-order='[[ 1, "asc" ]]' data-page-length='25'>
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Number
                </th>
            </tr>
        </thead>
        <tbody>
            {% for d in data %}
                <tr>
                    <td>
                        {{d.name}}
                    </td>
                    <td>
                        {{d.number}}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/js/index.html
{% extends 'base.html' %}
{% block content %}

    <form action="{% url 'js:search' %}" method="post">
        {% csrf_token%}
        <input type="text" name="search" />
        <input type="submit" value="Search" />
    </form>

    <table id="myTable">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Number
                </th>
            </tr>
        </thead>
        {% for d in data %}
            <tbody>
                <tr>
                    <td>
                        {{d.name}}
                    </td>
                    <td>
                        {{d.number}}
                    </td>
                </tr>
            </tbody>
        {% endfor %}
    </table>

{% endblock %}

templates/js/search.html
{% extends 'base.html' %}
{% block content %}

    <table>
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Number
                </th>
            </tr>
        </thead>
        {% for d in data %}
            <tbody>
                <tr>
                    <td>
                        {{d.name}}
                    </td>
                    <td>
                        {{d.number}}
                    </td>
                </tr>
            </tbody>
        {% endfor %}
    </table>

{% endblock %}